Terraform 1
Otus-DevOps-22-08/catalogoanatom_infra pull request #7
Opened 2022-10-26 00:15 UTC by catalogoanatom

# Выполнено ДЗ №

 - [*] Основное ДЗ

## PR checklist
 - [*] Выставил label с номером домашнего задания
 - [*] Выставил label с темой домашнего задания

2022-10-26 17:19 UTC, mrgreyves requested changes
Здравствуйте!
Проверил ваше дз
Оставил комментарии
Так же дополнительно стоит поработать с конфликтами
ДЗ возвращаю на доработку

2022-10-26 17:19 UTC, mrgreyves commented on terraform/.terraform.lock.hcl
> +# This file is maintained automatically by "terraform init".
Лишний файл

2022-10-26 17:19 UTC, mrgreyves commented on terraform/main.tf
> +  required_version = ">= 0.13"
Блок определения провайдера лучше удалить перед коммитом

2022-10-26 17:19 UTC, mrgreyves commented on packer/variables.json.example
> +  "service_account_key_file": "/home/amartynov/sec/key.json",
Проблема с ключом
Стоит дополнительно починив методом добавления фейкового ключа в репозиторий

2022-11-06 22:35 UTC, catalogoanatom commented on terraform/.terraform.lock.hcl
> +# This file is maintained automatically by "terraform init".
Добавил .terraform.* в .gitignore

2022-11-06 22:35 UTC, catalogoanatom commented on terraform/main.tf
> +  required_version = ">= 0.13"
Убрал вырсию

2022-11-06 22:36 UTC, catalogoanatom commented on packer/variables.json.example
> +  "service_account_key_file": "/home/amartynov/sec/key.json",
Исправлено в packer_base жду PR

2022-11-06 23:31 UTC, catalogoanatom commented on terraform/main.tf
> +  required_version = ">= 0.13"
Видимо я чтото не  понял. Если я уберу этот блок, не прокатит terraform init, terraform validate

2022-11-06 23:31 UTC, catalogoanatom commented
terraform validate -var-file=terraform.tfvars.example` stdout should match "Terraform has been successfully initialized!"
НЕ понимаю. Есть
terraform **plan** -var-file=terraform.tfvars.example 
но не
terraform **validate** -var-file=terraform.tfvars.example

2022-11-08 12:07 UTC, mrgreyves requested changes
Здравствуйте!)
Стоит подмержить себе изменения из ветки с пакером
Так же попробуйте перед пушем "закомментить" кусок кода терраформа с объявлением провайдера

2022-11-08 12:09 UTC, mrgreyves requested changes
Нужно попробовать поправить

2022-11-08 20:09 UTC, catalogoanatom commented
закоментил, тесты ублажились, но локально получается манифест не работает. :(

`
$ terraform validate
╷
│ Error: Missing required provider
│ 
│ This configuration requires provider registry.terraform.io/hashicorp/yandex, but that provider isn't available. You may be
│ able to install it automatically by running:
│   terraform init
╵

amartynov in ~/src/OTUS/catalogoanatom_infra/terraform (terraform-1)
$ terraform init

Initializing the backend...

Initializing provider plugins...
- Finding latest version of hashicorp/yandex...
╷
│ Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider hashicorp/yandex: provider
│ registry.terraform.io/hashicorp/yandex was not found in any of the search locations
│ 
│   - provider mirror at https://terraform-mirror.yandexcloud.net/
╵

`

2022-11-10 17:11 UTC, mrgreyves approved these changes
Здравствуйте!)
Разница в версиях терраформа и разница в объявлении провайдеров
ДЗ принимаю =)

2022-11-10 23:00 UTC, merged