Terraform 2
Otus-DevOps-22-08/catalogoanatom_infra pull request #8
Opened 2022-11-11 23:38 UTC by catalogoanatom

# Выполнено ДЗ № 7

 - [*] Основное ДЗ
 - [*] Задание со *

## В процессе сделано:
- all till page 29

## Как запустить проект:
terraform plan
terraform apply in stage/prod

## PR checklist
 - [*] Выставил label с номером домашнего задания
 - [*] Выставил label с темой домашнего задания

2022-11-12 12:13 UTC, mrgreyves requested changes
Здравствуйте!)
Проверил ваше дз
Рекомендую свериться с результатами тестов
Нужно поправить некоторые файлы
Там не долго =)
ДЗ возвращаю на доработку =)

2022-11-13 12:17 UTC, catalogoanatom commented
Я добавил фекуовые файлы и каталоги на основании ошибок тестов, но в ДЗ о них нет ни слова:
modules/vpc
terraform/storage-bucket.tf

2022-11-13 16:40 UTC, mrgreyves approved these changes
Здравствуйте!)
Апрув ^_^

2022-11-13 16:40 UTC, mrgreyves commented on terraform/storage-bucket.tf
> +  access_key = "YCAJEk47-PZ_hlO95-1sxzp-PM"
Надеюсь что ключики действительно фейковые =)

2022-11-15 10:40 UTC, merged